config/routes.rb
BuenosDias::Application.routes.draw do
  devise_for :users

  resources :phrases

  get "quotes/new"

  get "quotes/create"

  get "quotes/delete"

  get "quotes/edit"

  get "quotes/show"

  get "quotes/update"

  root :to => 'static_pages#home'
  
  match "/about" => "static_pages#about"

  get "static_pages/contact"

end

app/models/phrase.rb
class Phrase < ActiveRecord::Base
  attr_accessible :happy_quote
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  attr_accessible :quote
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/phrases_controller.rb
class PhrasesController < ApplicationController
  before_filter :authenticate_user!, :only => [:index, :edit, :create, :destroy, :new, :post, :update]
  # GET /phrases
  # GET /phrases.json
  def index
    @phrases = Phrase.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @phrases }
    end
  end

  # GET /phrases/1
  # GET /phrases/1.json
  def show
    @phrase = Phrase.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @phrase }
    end
  end

  # GET /phrases/new
  # GET /phrases/new.json
  def new
    @phrase = Phrase.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @phrase }
    end
  end

  # GET /phrases/1/edit
  def edit
    @phrase = Phrase.find(params[:id])
  end

  # POST /phrases
  # POST /phrases.json
  def create
    @phrase = Phrase.new(params[:phrase])

    respond_to do |format|
      if @phrase.save
        format.html { redirect_to @phrase, notice: 'Phrase was successfully created.' }
        format.json { render json: @phrase, status: :created, location: @phrase }
      else
        format.html { render action: "new" }
        format.json { render json: @phrase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /phrases/1
  # PUT /phrases/1.json
  def update
    @phrase = Phrase.find(params[:id])

    respond_to do |format|
      if @phrase.update_attributes(params[:phrase])
        format.html { redirect_to @phrase, notice: 'Phrase was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @phrase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phrases/1
  # DELETE /phrases/1.json
  def destroy
    @phrase = Phrase.find(params[:id])
    @phrase.destroy

    respond_to do |format|
      format.html { redirect_to phrases_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@phrase = Phrase.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @phrase }
    end
  end

  def about
  end

  def contact
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def random_phrase
		Phrase.first(order: "RANDOM()")
	end
end

app/helpers/phrases_helper.rb
module PhrasesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

	<%= favicon_link_tag 'favicon.ico' %>
	
		<link href='http://fonts.googleapis.com/css?family=Quicksand' rel='stylesheet' type='text/css'>

  <title>GOOD MORNING</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/phrases/_form.html.erb
<%= form_for(@phrase) do |f| %>
  <% if @phrase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phrase.errors.count, "error") %> prohibited this phrase from being saved:</h2>

      <ul>
      <% @phrase.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :happy_quote %><br />
    <%= f.text_field :happy_quote %>
  </div>
  <div class="actions">
    <%= f.submit 'Guardar Quote' %>
  </div>
<% end %>

app/views/phrases/edit.html.erb
<h1>Editing phrase</h1>

<%= render 'form' %>

<%= link_to 'Show', @phrase %> |
<%= link_to 'Back', phrases_path %>

app/views/phrases/index.html.erb
<h1>Listing phrases</h1>

<table>
  <tr>
    <th>Happy quote</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @phrases.each do |phrase| %>
  <tr>
    <td><%= phrase.happy_quote %></td>
    <td><%= link_to 'Show', phrase %></td>
    <td><%= link_to 'Edit', edit_phrase_path(phrase) %></td>
    <td><%= link_to 'Destroy', phrase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Phrase', new_phrase_path %>

app/views/phrases/new.html.erb
<h1>New phrase</h1>

<%= render 'form' %>

<%= link_to 'Back', phrases_path %>

app/views/phrases/show.html.erb
<div class="my-background">

<div class="my-background-<%= rand(1..20) %>">

	<a href="https://twitter.com/share" class="twitter-share-button" data-text="Good morning!" data-size="large">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

<%= link_to 'Home', root_path, class: "my-link-class" %>

<%= link_to 'About', about_path, class: "my-link-class" %>


	<p id="notice"><%= notice %></p>

<%= link_to(random_phrase) do %>

	<div class="phrase"> <%= @phrase.happy_quote %> </div>

<% end %>


</div>

app/views/static_pages/about.html.erb
<%= link_to 'Home', root_path, class: "my-link-class" %>
<div class="">
	<%= image_tag("solecillo.gif", :alt => "sun", :class => "img-sun")  %> 
</div>
<div class="textabout">
<h1>Hello there!<h1>
<p>Good Morning is a happy App made so you can start your day with a big smile on your face, or tweet a happy good morning phrase to someone you know, love or have a crush on.</p>

<p>Good Morning was built on Ruby On Rails, HTML, CSS, Git/Github, Heroku, markers and Adobe Illustrator.</p>

<p>By <a href="http://lilamiller.me" target=_blank> Lila Miller</a></p>
</div>

<a href="http://lilamiller.me" target=_blank class="name-tag"> by Lila Miller </a>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<div class="">
	<%= image_tag("solecillo.gif", :alt => "sun", :class => "img-sun")  %> 
</div>

<%= link_to "GOOD MORNING!", random_phrase, class: "big-button" %>

<div class="name-tag">
	<a href="http://lilamiller.me" target=_blank class="name-tag"> by Lila Miller </a>
</div>